name: assincrono
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.10.8

dependencies:
  path: ^1.9.0
  http: ^1.3.0
  # Correção: O path deve apontar para a pasta do pacote local
  command_runner:
    path: ./command_runner

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
